accounts/urls.py
from django.conf.urls  import url 
from . import views

app_name='accounts'

urlpatterns=[
url(r'^signup/$',views.signup_view,name="signup"),
url(r'^login/$',views.login_view,name="login"),
url(r'^logout/$',views.logout_view,name="logout")

]

blog/urls.py
from django.conf.urls import url



from . import views
app_name='blog'

urlpatterns = [
    url(r'^about/$',views.about),
    url(r'^article/',views.article, name='list'),
    url(r'^$',views.home),
    url(r'^(?P<slug>[\w-]+)/$',views.article_detail,name="detail")
]

djangoB/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings 


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^blog/',include('blog.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
	title=models.CharField(max_length=100)
	slug=models.SlugField()
	body=models.TextField()
	date=models.DateTimeField(auto_now_add=True)
	thumb = models.ImageField(default='default.png',blank=True)


	#add in thumbnail later
	#add in author later

	# python manage.py makemigration
	# python manage.py migrate
	



	def __str__(self):
		return self.title


	def snippet(self):
		return self.body[:70]+'..'

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
# Create your views here.signup_view
from django.contrib.auth import login,logout

def signup_view(request):
	if request.method =='POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('blog:list')
	else:
		form = UserCreationForm()
	return render(request,'signup.html',{'form':form})      

def login_view(request):
	if request.method =='POST':
		form= AuthenticationForm(data=request.POST)
		if form.is_valid():
			return redirect('blog:list')
	else:
		form = AuthenticationForm()
		return render(request,'login.html',{'form':form})

def logout_view(request):
	if request=='POST':
		logout(request)
		return redirect('blog:list')

blog/views.py
from django.http import HttpResponse
from django.shortcuts import render

from .models import Article


def home(request):
	return render(request,'home.html')

def about(request):
	return render(request,'about.html')


def article(request):
	articles = Article.objects.all().order_by('date')
	return render(request,'article.html',{ 'articles':articles })

def article_detail(request,slug):
	# return HttpResponse(slug)
	article = Article.objects.get(slug=slug)
	return render(request,'articled.html',{'article':article})

djangoB/views.py
from django.http import HttpResponse
from django.shortcuts import render


def home(request):
	return render(request,'home.html')

def about(request):
	return render(request,'about.html')


def article(request):
	return render(request,'article.html')

accounts/templates/login.html
{% extends 'base.html' %}



{% block content %}

	<h1>Login</h1>
	<form class="site-form" action="/accounts/login/" method="post">
		{% csrf_token %}
		{{form}}

<input type="submit" value="Login">
</form>
{% endblock %}

accounts/templates/signup.html
{% extends 'base.html' %}



{% block content %}

	<h1>Signup</h1>
	<form class="site-form" action="/accounts/signup/" method="post">
		{% csrf_token %}
		{{form}}

<input type="submit" value="Signup">
</form>
{% endblock %}

blog/templates/about.html
<html>
	<head>
		<meta charset="utf-8">
		<title>About</title>
	</head>
	<body>
		<h1>About Us</h1>
		<p>We like Django</p>
	</body>
</html>

blog/templates/article.html
	{% extends 'base.html' %}

	{% block content %}
		<h1>Article List</h1>
	
		<p>This is Article Liste</p>
		<div class="articles">
			{% for article in articles %}
		<div class="article">
			<h2><a href="{% url 'blog:detail' slug=article.slug %}">{{article.title}}</a></h2>
			<p>{{article.snippet}}</p>
			<p>{{article.date}}</p>
		</div>
			{% endfor %}

		</div>


{% endblock %}

blog/templates/articled.html
	{% extends 'base.html' %}
	{% block content %}
	<div class="article_detail">
		<div class="article">
			<img src="{{article.thumb.url}}"/>
			<h2>{{article.title}}</h2>
			<p>{{article.body}}</p>
			<p>{{article.date}}</p>

	</div>

	{% endblock %}

blog/templates/base.html
{% load static from staticfiles %}
<html>
	<head>
		<meta charset="utf-8">
		<title>Article</title>
			<link rel="stylesheet" href="{% static 'style.css' %}">
	</head>
	<body>
	<div class="wrapper">
		<h1><a href="{% url 'blog:list' %}">Home</a></h1>
		<nav>
			<ul>
			<li>
				<form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
					{% csrf_token %}
					<button type="submit">Logout</button>
				</form>
					
			</li>	

			</ul>
		</nav>
		{% block content %}
		{% endblock %}
	</body>
</html